### ISSUE TITLE
Set-SCManagerPermission NETWORK (S-1-5-2) ACL is never removed

### ISSUE THREAD

**Issue by Borgquite** [p0w3rsh3ll/SCManager#1]
In the function Set-SCManagerPermission lines 119-135 there is code to remove the NETWORK ACL before it is added again.

However due to an error in line 119 this never executes (can be seen by running the command twice, with $VerbosePreference set):

```
PS C:\WINDOWS\system32> $VerbosePreference = "Continue"
PS C:\WINDOWS\system32> Set-SCManagerPermission
VERBOSE: Successfully added AccessDenied for NT AUTHORITY\NETWORK
VERBOSE: <redacted>
VERBOSE: Successfully set binary ACL in the registry

PS C:\WINDOWS\system32> Set-SCManagerPermission
VERBOSE: Successfully added AccessDenied for NT AUTHORITY\NETWORK
VERBOSE: <redacted>
VERBOSE: Successfully set binary ACL in the registry
```

Easy to fix - just remove the IF statement. The `Where-Object { $_.SecurityIdentifier.Value -eq 'S-1-5-2' }` in the following line already ensures that the script 'does nothing' if there is no S-1-5-2 entry in the existing ACL.

Pull request to follow.

**Comment by p0w3rsh3ll** [comment]
Thank you for your contribution 👍
