### ISSUE TITLE
SCSet commands only set DACL, not SACL

### ISSUE THREAD

**Issue by Borgquite** [p0w3rsh3ll/SCManager#3]
When you replace the existing security descriptor with the 'updated' one, the SDDL syntax generated by GetSddlForm is currently only outputting the DACL, not the whole security descriptor (including the SACL).

So what you are 'getting' from sc.exe sdshow scmanager includes the SACL at the end: e.g.

D:(A;;CCLCRPRC;;;IU)(A;;CCLCRPRC;;;SU)(A;;CC;;;AU)(A;;CCLCRPWPRC;;;SY)(A;;KA;;;BA)(A;;CCLCRPRC;;;S-1-5-21-2668863397-291452949-3734950744-1020)(A;;CC;;;AC)(A;;CC;;;S-1-15-3-1024-528118966-3876874398-709513571-1907873084-3598227634-3698730060-278077788-3990600205)**_S:(AU;FA;KA;;;WD)(AU;OIIOFA;GA;;;WD)_**

But what you are 'sending' to sc.exe sdset scmanager does **not** include the SACL:

D:(D;;KA;;;NU)(A;;CCLCRPRC;;;IU)(A;;CCLCRPRC;;;SU)(A;;CC;;;AU)(A;;CCLCRPWPRC;;;SY)(A;;KA;;;BA)(A;;CCLCRPRC;;;S-1-5-21-2668863397-291452949-3734950744-1020)(A;;CC;;;AC)(A;;CC;;;S-1-15-3-1024-528118966-3876874398-709513571-1907873084-3598227634-3698730060-278077788-3990600205)

This _seems_ to be working, but doesn't appear to be the [officially supported](https://www.betaarchive.com/wiki/index.php/Microsoft_KB_Archive/907460) way to use sdset - most guides online [appear](https://pitstop.manageengine.com/portal/en/kb/articles/set-permissions-to-service-control-manager-security-for-non-admin-domain-user-in-windows-service-monitoring-wmi) [to](https://www.ibm.com/docs/en/taddm/7.3.0?topic=discovery-setting-up-sc-manager-access-ibmcol) [recommend](https://doc.spotlightcloud.io/monitoring-windows/connection/wmi/wmi-minimumpermissions/) including the SACL in the sdset command when attempting to update the security descriptor.

It's an easy fix - when you call GetSddlForm, just change `[System.Security.AccessControl.AccessControlSections]::Access` to `[System.Security.AccessControl.AccessControlSections]::All`

Pull request to follow.

**Comment by p0w3rsh3ll** [comment]
Thank you for your contribution 👍
